### ISSUE TITLE
stendhal contains non-free sprites

### ISSUE THREAD

**Issue by Zefk** [saniv/free-game-art-topdown#1]
I have discovered over 60 RPG Maker 2003 edits or resizes and a few RPG maker XP edits. RPG maker sprites are only allowed in RPG maker engines that one has purchased. They are not opensource.

https://github.com/saniv/free-game-art-topdown/tree/master/topdown/stendhal

You should honestly download the RPG Maker RTP packs and check for more. I will list the folder directory name and files. It is a RPG Maker 2003 edits unless I mention RPG Maker XP. All I ask is that you inform me of more edits. 

**/monsters/amazon:**

-amazoness_archer_commander
-amazoness_commander

**npc/animal:**

-dog
-Small_dog
-kitten

**/monsters/animal:**

-Slimes (all of them)
-Tiger
-lion

**/monsters/farm_animals:**

-Chick
-Cow
-Bull
-Ram
-White horse
-Horse
-beaver (XP Edit)

**/monsters/flying_beast:**

-bluebird
-carnary
-pink_bird
-green_bird
-Peach_bird
-red_brid
-seagull

All the birds are rmxp edits.

**/monsters/minotaur:**

-Mino_king
-Minotaur

**/monsters/sheepmen:**

-All of them are edits

**/monsters/golem:**

-stone_golem

**/monsters/huge_animal:**

-chaos_green_dragonrider
-chaos_red_dragonrider
-red_dragon
-Green_dragon
-Black_death
-Golden_Death
-flying_golden_dragon
-twin_head_dragon

**/monsters/human:**

-littlewizard
-armored_leader
-armorer_leader
-armored_warrior
-super_human

**/monsters/myhical_animal:**

-gashadokuro

**/monsters/troll:**

-red_troll
-Troll

**/monsters/undead:**

-Ghost
-Death

**/npc:**

-boynpc
-chessplayernpc
-Childnpc
-deadmannpc
-gardenernpc
-man_000_npc
-man_006_npc
-oldmannpc
-princessnpc
-Mothernpc
-armorleadernpc
-Kingnpc
-kingcozartnpc
-woman_003_npc
-youngkingnpc
-stormtroopernpc

**/npc (Can be debated on:)**

Some features look like edits or resizes.

-mithrilforgernpc (hat)
-plinknpc (hair)

**Other: (two sprites on one spritesheet)**

-cat.png (big cat is okay, little cat is an edit.)

**Comment by Zefk** [comment]
in folder:

**monsters/ent:**
-dead_ent

![browntree](http://i.imgur.com/bNw3VzQ.png)

The dead ent is an edit of the brown tree here:
http://www.hbgames.org/forums/viewtopic.php?t=78803&p=929850

**Comment by Zefk** [comment]
**monsters/human:**
-soldier_wizard (hat)

**Comment by saniv** [comment]
Hi! I have removed all stendhal art from the repository. Its source is very dubious.

**Comment by Zefk** [comment]
On further inspection...some of it looks like painted edits. I think that was the right course of action.
